# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
  args = {
    name = "hammerjs";
    packageName = "hammerjs";
    version = "2.0.8";
    src = ./.;
    buildInputs = globalBuildInputs;
    meta = {
      description = "A javascript library for multi-touch gestures";
      homepage = http://hammerjs.github.io/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}